# Generated by Django 5.1 on 2024-11-02 20:00

import ckeditor_uploader.fields
import django.utils.timezone
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_alter_project_created_alter_project_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(default=django.utils.timezone.now, verbose_name='contenido'),
            preserve_default=False,
        ),
    ]
